[loggers]
keys=root

[handlers]
keys=console,file

[formatters]
keys=standard

[logger_root]
level=WARNING
handlers=console,file

[handler_console]
class=StreamHandler
level=WARNING
formatter=standard
args=(sys.stdout,)

[handler_file]
class=FileHandler
level=WARNING
formatter=standard
args=('birthday.log', 'a')

[formatter_standard]
format=%(asctime)s | %(levelname)s | %(name)s | %(message)s
datefmt=%Y-%m-%d %H:%M:%S