create table if not exists people (
    id bigint generated by default as identity primary key,
    name text not null,
    birthday_month smallint not null
        check (birthday_month between 1 and 12),
    birthday_day smallint not null
        check (birthday_day between 1 and 31)
);

create table if not exists recipients (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique
);

create table if not exists person_recipients (
    person_id bigint not null
        references people(id)
        on delete cascade,

    recipient_id bigint not null
        references recipients(id)
        on delete cascade,

    primary key (person_id, recipient_id)
);