name: Birthday Reminder

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  remind-birthday:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run birthday reminder
        env:
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

          EMAIL_HOST: ${{ vars.EMAIL_HOST}}
          EMAIL_PORT: ${{ vars.EMAIL_PORT}}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python -m main